### ISSUE TITLE
Error Using Graphene Django with Polymorphic (typed models)

### ISSUE THREAD

**Issue by MichaelrMentele** [graphql-python/graphene-django#276]
I am trying to query a field `source` on a model called `Requirement` which can have a `source` which is a `pool` however `pool` is polymorphic. That is, it is a typed model.

```python 
Pool(TypedModel):
   ...

ManufacturedLabwarePool(Pool):
  ...
```

When I try to query `source` as a field on `Requirement` I get the following error:

![image](https://user-images.githubusercontent.com/9519712/30709338-bbf964e8-9eb6-11e7-9d27-465581f73158.png)

I'm not sure how to resolve this so that we do not expect a specific type for a given field.

**Comment by MichaelrMentele** [comment]
When I have a polymorphic table which can have various types using Django typed models I either get a conflict in the schema definition if I try to define a type in the schema on the backend or in graphiql on the client (if I define one top level type).

Trace for schema that looks like:
![image](https://user-images.githubusercontent.com/9519712/30757383-5ced388a-9f83-11e7-80e7-675aad67c4d8.png)

```
[2017-09-22 10:41:43,369][624:139746736154368][base.py/handle_uncaught_exception][ERROR] Internal Server Error: /graphql
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 63, in view
    self = cls(**initkwargs)
  File "/usr/local/lib/python2.7/dist-packages/graphene_django/views.py", line 70, in __init__
    schema = graphene_settings.SCHEMA
  File "/usr/local/lib/python2.7/dist-packages/graphene_django/settings.py", line 116, in __getattr__
    val = perform_import(val, attr)
  File "/usr/local/lib/python2.7/dist-packages/graphene_django/settings.py", line 60, in perform_import
    return import_from_string(val, setting_name)
  File "/usr/local/lib/python2.7/dist-packages/graphene_django/settings.py", line 74, in import_from_string
    module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/auto_pipeline_app/auto_pipeline/schema.py", line 153, in <module>
    schema = graphene.Schema(query=Query)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/schema.py", line 44, in __init__
    self.build_typemap()
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/schema.py", line 105, in build_typemap
    self._type_map = TypeMap(initial_types, auto_camelcase=self.auto_camelcase, schema=self)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 65, in __init__
    super(TypeMap, self).__init__(types)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/typemap.py", line 16, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 73, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 103, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/typemap.py", line 79, in reducer
    field_map = type.fields
  File "/usr/local/lib/python2.7/dist-packages/graphql/pyutils/cached_property.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/definition.py", line 180, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/definition.py", line 189, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 234, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 73, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 103, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/typemap.py", line 79, in reducer
    field_map = type.fields
  File "/usr/local/lib/python2.7/dist-packages/graphql/pyutils/cached_property.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/definition.py", line 180, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/definition.py", line 189, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 234, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 73, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 78, in graphene_reducer
    return self.reducer(map, type.of_type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 73, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 103, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/typemap.py", line 79, in reducer
    field_map = type.fields
  File "/usr/local/lib/python2.7/dist-packages/graphql/pyutils/cached_property.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/definition.py", line 180, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/definition.py", line 189, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 234, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 73, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 78, in graphene_reducer
    return self.reducer(map, type.of_type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 73, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 103, in graphene_reducer
    return GraphQLTypeMap.reducer(map, internal_type)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/typemap.py", line 79, in reducer
    field_map = type.fields
  File "/usr/local/lib/python2.7/dist-packages/graphql/pyutils/cached_property.py", line 16, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/definition.py", line 180, in fields
    return define_field_map(self, self._fields)
  File "/usr/local/lib/python2.7/dist-packages/graphql/type/definition.py", line 189, in define_field_map
    field_map = field_map()
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 234, in construct_fields_for_type
    map = self.reducer(map, field.type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 73, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 78, in graphene_reducer
    return self.reducer(map, type.of_type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 73, in reducer
    return self.graphene_reducer(map, type)
  File "/usr/local/lib/python2.7/dist-packages/graphene/types/typemap.py", line 84, in graphene_reducer
    ).format(_type.graphene_type, type)
AssertionError: Found different types with the same name in the schema: PoolType, PoolType.
```

If I define only the PoolNode type then I have a client side error in graphiql like so:
![image](https://user-images.githubusercontent.com/9519712/30757429-946e7648-9f83-11e7-9bb6-bcf95a620df9.png)

**Comment by MichaelrMentele** [comment]
If I use a union (and I may be doing this incorrectly) but if I union all of the `Pool` types and use that as the field I still get the above error. Do I need to use fragments for every polymorphism of the pools table?

**Comment by MichaelrMentele** [comment]
There seems to be an issue where the type on the backend resolves to the correct base type but the type that is serialized and checked on the client shows up as the 'type' field stored on the typed model. I think this will be any easy fix, perhaps change the way serialization happens, will need to dig into the source for Graphene @syrusakbary

**Comment by atakanarikan** [comment]
Hey @MichaelrMentele, were you able to solve this problem? I'm having a similar issue with graphene-django and django-polymorphic.

**Comment by flesser** [comment]
I'm also trying to use `graphene-django` with `django-polymorphic` and run into the same issue.

**Comment by chessbr** [comment]
I was able to solve this by using:

- https://stackoverflow.com/a/49575572
- https://github.com/graphql-python/graphene/issues/493

**Comment by lucas-bremond** [comment]
@chessbr Would you mind sharing the solution?
