### ISSUE TITLE
Is it possible not to print error stacktrace on specific type of errors (client errors, eg ValidationError)

### ISSUE THREAD

**Issue by vaniakosmos** [graphql-python/graphene-django#413]
related: https://github.com/graphql-python/graphql-core/issues/142

**Comment by vaniakosmos** [comment]
partially solved this by adding logger filter in settings file:
```
class Filter(logging.Filter):
    def filter(self, record):
        err_type, err_obj, traceback = record.exc_info
        return not isinstance(err_obj, AppException)

logging.getLogger('graphql.execution.executor').addFilter(Filter())
```

But `GraphQLLocatedError` still shows up:
```
Traceback (most recent call last):
  File "/Users/Vania/.pyenv/versions/test/lib/python3.6/site-packages/graphql/execution/executor.py", line 330, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/Users/Vania/.pyenv/versions/test/lib/python3.6/site-packages/graphql/execution/executor.py", line 383, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: User is not authenticated.
```

**Comment by vaniakosmos** [comment]
and the problem lies inside graphql.execution.executor, line 340:
```
    except Exception as e:
        traceback = sys.exc_info()[2]
        exe_context.report_error(e, traceback)
        return None
```
instead of logging it with already created `logger`

**Comment by vaniakosmos** [comment]
well, looks like it is already fixed, but not updated on pypi
