### ISSUE TITLE
Failed to run migrate in cookbook example

### ISSUE THREAD

**Issue by MeiK-h** [graphql-python/graphene-django#418]
[Defining our models](http://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/#defining-our-models)

The following error occurred when I ran this example 
```
$ python3 manage.py migrate
Traceback (most recent call last):
  File "/Users/meik/cookbook/env/lib/python3.6/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'cookbook' has no attribute 'ingredients'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/meik/cookbook/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/meik/cookbook/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/meik/cookbook/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/meik/cookbook/env/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Users/meik/cookbook/env/lib/python3.6/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/Users/meik/cookbook/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cookbook.ingredients'
```

I tried to modify the code

before
```python
INSTALLED_APPS = [
    ...
    # Install the ingredients app
    'cookbook.ingredients',
]
```

after
```python
INSTALLED_APPS = [
    ...
    # Install the ingredients app
    'ingredients.apps.IngredientsConfig',
]
```

Am I wrong? Or is the sample code problematic?

English is not my native language; please excuse typing errors.

**Comment by MeiK-h** [comment]
Sorry, it seems that I have made a mistake with the file structure.
