### ISSUE TITLE
intermittent failures (400) while executing queries

### ISSUE THREAD

**Issue by danaronson** [graphql-python/graphene-django#425]
We are using 2.0.0 and occasionally see 400 errors.  It looks like the sync executor (default) invoked in view.py isn't resolving the promise when it should be.  Any thoughts?

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/graphene_django/views.py", line 275, in execute_graphql_request
    executor=self.executor,
  File "/usr/local/lib/python2.7/site-packages/graphene_django/views.py", line 234, in execute
    return execute(self.schema, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/graphql/execution/executor.py", line 83, in execute
    return promise.get()
  File "/usr/local/lib/python2.7/site-packages/promise/promise.py", line 422, in get
    self._wait(timeout or DEFAULT_TIMEOUT)
  File "/usr/local/lib/python2.7/site-packages/promise/promise.py", line 418, in _wait
    self.wait(self, timeout)
  File "/usr/local/lib/python2.7/site-packages/promise/promise.py", line 415, in wait
    return async_instance.wait(promise, timeout)
  File "/usr/local/lib/python2.7/site-packages/promise/async_.py", line 101, in wait
    self.drain_queue_until_resolved(target)
  File "/usr/local/lib/python2.7/site-packages/promise/async_.py", line 83, in drain_queue_until_resolved
    fn._settle_promises()
  File "/usr/local/lib/python2.7/site-packages/promise/promise.py", line 385, in _settle_promises
    self._settle_promise0(self._fulfillment_handler0, value, None)
  File "/usr/local/lib/python2.7/site-packages/promise/promise.py", line 280, in _settle_promise0
    self._settle_promise(promise, handler, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/promise/promise.py", line 264, in _settle_promise
    handler(value)  # , promise
  File "/usr/local/lib/python2.7/site-packages/promise/promise_list.py", line 93, in _promise_fulfilled
    self._resolve(self._values)
  File "/usr/local/lib/python2.7/site-packages/promise/promise_list.py", line 111, in _resolve
    assert not self.is_resolved
AssertionError
```

**Comment by phalt** [comment]
@danaronson did you resolve this issue?

**Comment by dopeboy** [comment]
Closing this down due to inactivity.
