### ISSUE TITLE
ForeignKey causes Django error "Models aren't loaded yet"

### ISSUE THREAD

**Issue by lucasmyers** [graphql-python/graphene-django#459]
I'm using a standard Django setup with graphene (using the standard `db.sqlite3` for now), but as soon as I add a ForeignKey field to one of my models and try `python manage.py makemigrations`, Django throws an error. I know this is not a Django issue because when I removed `graphene_django` from my installed apps (and removed `graphql` from `urls.py`), I was able to migrate and serve the app with no errors. Any help is greatly appreciated!

Versions:
Python v3.5.2
Django v2.0.5
graphene v2.1.2
graphene-django v2.0.0

My models.py file:
```from django.db import models
from django.conf import settings
from graphene_django.types import DjangoObjectType
import uuid


class MLProject(models.Model):
    title = models.TextField()
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tenant = models.CharField(max_length=500)
    owner = models.CharField(max_length=500)
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.title


def pickle_file_path(instance, filename):
    return settings.PICKLE_ROOT + ('{0}/{1}/'.format(instance.project.tenant, instance.project.owner)) + filename


class MLModel(models.Model):
    name = models.TextField()
    algorithm = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, blank=True, null=True)
    pickle = models.FileField(upload_to=pickle_file_path, null=True, blank=True)
    project = models.ForeignKey(MLProject, on_delete=models.CASCADE)
    # the above line is what causes the error; if commented, the app migrates and serves just fine

    def __str__(self):
        return self.name


class MLProjectType(DjangoObjectType):
    class Meta:
        model = MLProject


class MLModelType(DjangoObjectType):
    class Meta:
        model = MLModel

```

Error output:
```Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/mysite/myapp/models.py", line 46, in <module>
    class MLModelType(DjangoObjectType):
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene/pyutils/init_subclass.py", line 17, in __init__
    super_class.__init_subclass__.__func__(cls, **kwargs)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene/utils/subclass_with_meta.py", line 48, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene_django/types.py", line 65, in __init_subclass_with_meta__
    construct_fields(model, registry, only_fields, exclude_fields),
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene_django/types.py", line 30, in construct_fields
    converted = convert_django_field_with_choices(field, registry)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene_django/converter.py", line 59, in convert_django_field_with_choices
    return convert_django_field(field, registry)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene_django/converter.py", line 173, in convert_field_to_djangomodel
    model = field.related_model
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/db/models/fields/related.py", line 94, in related_model
    apps.check_models_ready()
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/apps/registry.py", line 132, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
(env) lucasmyers@Evel-Knievel ~/Documents/bigsense/graphql_test/mysite $ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/mysite/myapp/models.py", line 40, in <module>
    class MLModelType(DjangoObjectType):
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene/pyutils/init_subclass.py", line 17, in __init__
    super_class.__init_subclass__.__func__(cls, **kwargs)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene/utils/subclass_with_meta.py", line 48, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene_django/types.py", line 65, in __init_subclass_with_meta__
    construct_fields(model, registry, only_fields, exclude_fields),
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene_django/types.py", line 30, in construct_fields
    converted = convert_django_field_with_choices(field, registry)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene_django/converter.py", line 59, in convert_django_field_with_choices
    return convert_django_field(field, registry)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/functools.py", line 743, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/graphene_django/converter.py", line 173, in convert_field_to_djangomodel
    model = field.related_model
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/db/models/fields/related.py", line 94, in related_model
    apps.check_models_ready()
  File "/Users/lucasmyers/Documents/bigsense/graphql_test/env/lib/python3.5/site-packages/django/apps/registry.py", line 132, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by pinhao1994** [comment]
@lucasmyers 
Here is the solution: https://groups.google.com/d/msg/wagtail/E4Hv4rIlPNw/vL4VRa_tAAAJ
```python
class MLProjectType(DjangoObjectType):
    class Meta:
        model = MLProject


class MLModelType(DjangoObjectType):
    class Meta:
        model = MLModel
```
Just put this part of code into other script such as **model_types.py**
And fix the *import path* issue and this should work.
