### ISSUE TITLE
Running into Import DateTime issue

### ISSUE THREAD

**Issue by cgsmith** [graphql-python/graphene-django#501]
I'm fairly new to django and python so I hope this is most likely some naivety. 

I am experiencing this issue while running Python 3.6.6 in the python:3.6 docker container - 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/graphene_django/__init__.py", line 1, in <module>
    from .types import DjangoObjectType
  File "/usr/local/lib/python3.6/site-packages/graphene_django/types.py", line 9, in <module>
    from .converter import convert_django_field_with_choices
  File "/usr/local/lib/python3.6/site-packages/graphene_django/converter.py", line 4, in <module>
    from graphene import (
ImportError: cannot import name 'DateTime'  
```

I also tried to just import `DateTime` from the python command line and it errors out.

My main host is Windows 10 running Docker Toolbox. Any pointers or help on the issue would be greatly appreciated!

**Comment by jayhale** [comment]
What is the output of `pip freeze`?

**Comment by cgsmith** [comment]
out put of `pip freeze`

```
dateutils==0.6.6
Django==1.11.15
django-appconf==1.0.2
django-extensions==1.7.5
django-filter==1.0.4
django-froala-editor==2.4.2
django-measurement==2.4.0
django-multiselectfield==0.1.8
future==0.16.0
graphene==2.0.1
graphene-django==2.1.0
graphql-core==2.1
graphql-relay==0.4.5
iso8601==0.1.12
isoweek==1.3.3
jsonfield==2.0.2
mailchimp3==2.0.11
Markdown==2.6.7
measurement==1.8.0
nameparser==0.5.1
olefile==0.45.1
phonenumbers==8.8.8
Pillow==4.0.0
probableparsing==0.0.1
promise==2.1
pyDes==2.0.1
PyJWT==1.5.3
python-crfsuite==0.9.5
python-dateutil==2.6.1
pytz==2017.2
qrcode==5.3
raven==6.5.0
requests==2.13.0
Rx==1.6.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.11.0
stripe==1.46.0
sympy==0.7.6.1
typing==3.6.4
usaddress==0.5.10
validate-email==1.3                                               
```

**Comment by jayhale** [comment]
Your versions of graphene-django and graphene are mismatched.  graphene-django 2.1.0 requires graphene 2.1, you have 2.0.  See: https://github.com/graphql-python/graphene-django/blob/dc561c68c49d1a91637503f765857d819c36769a/setup.py#L51

May not be the source of the issue, but is a good place to start.
