### ISSUE TITLE
serializer_class is required for the SerializerMutation

### ISSUE THREAD

**Issue by gotexis** [graphql-python/graphene-django#595]
```python
Traceback (most recent call last):
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\e\AppData\Local\Programs\Python\Python37\Lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\django\views\generic\base.py", line 62, in view
    self = cls(**initkwargs)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\graphene_django\views.py", line 78, in __init__
    schema = graphene_settings.SCHEMA
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\graphene_django\settings.py", line 116, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\graphene_django\settings.py", line 55, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\graphene_django\settings.py", line 69, in import_from_string
    module = importlib.import_module(module_path)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\dev\proj\melar\config\schema.py", line 24, in <module>
    ObjType
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\graphene\utils\subclass_with_meta.py", line 52, in __init_subclass__
    super_class.__init_subclass_with_meta__(**options)
  File "C:\Users\e\.virtualenvs\melar-tgQDc0OS\lib\site-packages\graphene_django\rest_framework\mutation.py", line 60, in __init_subclass_with_meta__
    raise Exception("serializer_class is required for the SerializerMutation")
Exception: serializer_class is required for the SerializerMutation
```

_Originally posted by @hellpirat in https://github.com/graphql-python/graphene-django/issues/509#issuecomment-443104948_

**Comment by zbyte64** [comment]
The error has the explanation at the end, you have defined a `SerializerMutation` without specifying a `seiralizer_class`

**Comment by gotexis** [comment]
@zbyte64
Hey,

Actually, I believe there was some kind of error. I have checked the serializer mutation, it is there.

```python
class UserMutation(SerializerMutation):

    class Meta:
        serializer_class = UserSerializer
```

Then, when composing the mutations, cannot compose it like queries, I had to manually do this:

```
class Mutation(
    # UserMutation,  # < - put it here will cause error!
    ObjType
):
    user = UserMutation.Field()    # <- must put it like this
```

I hope this issue could be reopened

**Comment by zbyte64** [comment]
I believe standard practice is to have both `Query` and `Mutation` be defined as `ObjectType`s . Anyhow, which doc page did you consult?

**Comment by gotexis** [comment]
@zbyte64 Actually the fault was on my end... Oops

I believe what should have been done:

```python
class UserMutation(SerializerMutation):
    class Meta:
        serializer_class = UserSerializer

class AppMutation:
    user = UserMutation.Field()
    anthermodel = AnotherMutation.Field()

```
Then in the main schema:
```python
class ComposedMutation(
    UserMutation,
    AppMutation,
):
    pass
```

So basically there are 3 levels, I tried to compose serializer mutations together (2 levels), so the mutations overwrite each other...

LOL

**Comment by phalt** [comment]
Closing as resolved.
