### ISSUE TITLE
Django: ImportError: cannot import name 'ResolveInfo'

### ISSUE THREAD

**Issue by SpyTec** [graphql-python/graphene-django#737]
@SpyTec commented on [Wed Aug 07 2019](https://github.com/graphql-python/graphene/issues/1047)

Following the Relay walkthrough I'm getting the following error. Since it's quite cryptic
```py
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2935fa98c8>
Traceback (most recent call last):
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    autoreload.raise_last_exception()
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/graphene_django/__init__.py", line 1, in <module>
    from .types import DjangoObjectType
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/graphene_django/types.py", line 8, in <module>
    import graphene
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/graphene/__init__.py", line 3, in <module>
    from .types import (
  File "/home/spytec/code/.virtualenvs/Envs/telltale-server/lib64/python3.6/site-packages/graphene/types/__init__.py", line 2, in <module>
    from graphql import ResolveInfo
ImportError: cannot import name 'ResolveInfo'
```
`INSTALLED_APPS` here, where `graphql` is an app in my project
```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # This will also make the `graphql_schema` management command available
    'graphene_django',
    'debug_toolbar',
    'welcome',
    'api',
    'rest_framework',
    'django.contrib.sites',
    'drf_multiple_model',
    'filters',
    'drf_yasg',
    "django_cron",
    'corsheaders',
    'django_filters',
	# app part of the project
    'graphql',
]
```

**Comment by jkimbo** [comment]
@SpyTec can you run `pip freeze` and include the output?

**Comment by SpyTec** [comment]
I knew I was forgetting something. @jkimbo:
```
(telltale-server) spytec@Alioth:~/Documents/PythonProjects/telltale-server$ pip freeze
aniso8601==6.0.0
certifi==2018.8.24
chardet==3.0.4
coreapi==2.3.3
coreschema==0.0.4
Django==1.11.15
django-common-helpers==0.9.2
django-cors-headers==2.4.0
django-cron==0.5.1
django-debug-toolbar==1.8
django-filter==2.1.0
django-rest-multiple-models==2.1.1
djangorestframework==3.8.2
djangorestframework-bulk==0.2.1
djangorestframework-stubs==0.2.0
drf-url-filters==0.5.1
drf-yasg==1.10.2
factory-boy==2.11.1
Faker==1.0.0
graphene==2.1.7
graphene-django==2.4.0
graphql-core==2.2.1
graphql-relay==2.0.0
gunicorn==19.4.5
idna==2.7
inflection==0.3.1
itypes==1.1.0
Jinja2==2.10
MarkupSafe==1.0
memory-profiler==0.55.0
openapi-codec==1.3.2
promise==2.2.1
psutil==5.6.3
psycopg2==2.7.3.1
python-dateutil==2.7.5
pytz==2018.5
requests==2.19.1
ruamel.yaml==0.15.70
Rx==1.6.1
simplejson==3.16.0
singledispatch==3.4.0.3
six==1.11.0
sqlparse==0.2.4
text-unidecode==1.2
uritemplate==3.0.0
urllib3==1.23
voluptuous==0.11.5
whitenoise==3.3.1
```

**Comment by jkimbo** [comment]
Do you have a `graphql` folder inside your project?

**Comment by SpyTec** [comment]
Yes, would that cause an issue?

**Comment by jkimbo** [comment]
Yes because of the way that python resolves modules. Basically python will important local modules before site packages so the import line that’s failing is trying to import `ResolveInfo` from your local `graphql` module rather than the graphql-core package. More info here: https://docs.python.org/3/tutorial/modules.html#the-module-search-path

Unfortunately (if you don’t want to mess around with python paths which I wouldn’t recommend) the only solution is to change the name of your folder to something else.

**Comment by SpyTec** [comment]
Thanks for the info, that was the issue. Luckily it was a minor change since the app was newly created :)

Thanks for the very quick response

**Comment by scottralph** [comment]
> Yes because of the way that python resolves modules. Basically python will important local modules before site packages so the import line that’s failing is trying to import `ResolveInfo` from your local `graphql` module rather than the graphql-core package. More info here: https://docs.python.org/3/tutorial/modules.html#the-module-search-path
> 
> Unfortunately (if you don’t want to mess around with python paths which I wouldn’t recommend) the only solution is to change the name of your folder to something else.

This was exactly my problem -- thanks!
