### ISSUE TITLE
Can you subclass a mutation?

### ISSUE THREAD

**Issue by Siecje** [graphql-python/graphene-django#759]
```Python
class CreateProject(graphene.Mutation):
    id = graphene.ID()
    class Arguments:
        name = graphene.String(required=True)
    def mutate(self, info, **args):
        return CreateProject(id=1)


class CreateProject2(CreateProject):
    def mutate(self, info, **args):
        args['foo'] = 1
        return super().mutate(info, **args)


class Mutation(graphene.ObjectType):
    create_project = CreateProject2.Field()
```

I have subclassed a mutation but I'm getting this error.

```
Traceback (most recent call last):
  File "/home/cody/Desktop/cookbook/venv/lib/python3.7/site-packages/promise/promise.py", line 487, in _resolve_from_executor
    executor(resolve, reject)
  File "/home/cody/Desktop/cookbook/venv/lib/python3.7/site-packages/promise/promise.py", line 754, in executor
    return resolve(f(*args, **kwargs))
  File "/home/cody/Desktop/cookbook/venv/lib/python3.7/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/home/cody/Desktop/cookbook/cookbook/schema.py", line 20, in mutate
    return super().mutate(info, **args)
graphql.error.located_error.GraphQLLocatedError: 'super' object has no attribute 'mutate'
```

https://github.com/Siecje/graphene-help/blob/master/cookbook/schema.py#L12

Here is a small repo to reproduce the issue.

https://github.com/Siecje/graphene-help

**Comment by jkimbo** [comment]
@Siecje `mutate` is not actually a method on the class, it's a static method. If you update your code to this it should work:


```python
class CreateProject(graphene.Mutation):
    id = graphene.ID()
    class Arguments:
        name = graphene.String(required=True)

    def mutate(root, info, **args):
        return CreateProject(id=1)


class CreateProject2(CreateProject):
    def mutate(root, info, **args):
        args['foo'] = 1
        return CreateProject.mutate(root, info, **args)


class Mutation(graphene.ObjectType):
    create_project = CreateProject2.Field()
```
